name: Deploy infrastructure
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{  secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-2
    steps:
      - uses: actions/checkout@v3
      - name: setup s3 buckets
        run:  |
          cd infrastructure/scripts
          sh setup_terraform_bucket.sh
      - name: make zip for lambda function
        run:  |
          cd infrastructure/scripts
          sh make_zip_lambda_functions_src.sh
      - name: run terraform
        run:  |
          cd infrastructure
          terraform init
          terraform apply -auto-approve -var 'NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}'